import gradio as gr
import os

def generate_short(video_url):
    # Placeholder logic — buraya gerçek video işleme fonksiyonlarını bağlayabilirsin
    return f"Received video URL: {video_url}"

iface = gr.Interface(
    fn=generate_short,
    inputs=gr.Textbox(label="YouTube Video URL"),
    outputs="text",
    title="AI Short Creator",
    description="Paste a YouTube video link and get a short version generated by AI."
)

if __name__ == "__main__":
    iface.launch(server_name="0.0.0.0", server_port=int(os.environ.get("PORT", 8080)))
